name: Build Spring Boot Image
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Alternative: 'zulu'
          java-version: '21'

      # # Step 3: Cache Maven dependencies
      # - name: Cache Maven packages
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-maven

      # Step 4: Build the project and create Docker image
      - name: Build with Maven and create Docker image
        run: mvn spring-boot:build-image

      # (Optional) Step 5: Push the Docker image to a registry
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 5: Push the Docker image to ghcr.io
      - name: Log in to Docker ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}



      - name: Push Docker image
        run: |
          docker tag arcdz/pkgd:latest arcdz/pkgd:${{ github.sha }}
          docker push arcdz/pkgd:${{ github.sha }}
          docker push arcdz/pkgd:latest
