name: Spring Boot Docker Image
# Package with GitHub Actions |  maven-plugin | spring-boot:build-Image

# using SEMVER https://semver.org/
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # Checkout: https://github.com/marketplace?type=actions:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JAVA JDK: https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Alternative: 'zulu'
          java-version: '21'
          cache: 'maven'

      # Docker Metadata action: https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract metadata (tags, labels) for Docker # Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      # Debugging step: Print the generated tags
      - name: Print Docker tags
        run: echo ${{ steps.meta.outputs.tags }}

      # Docker Login: https://github.com/marketplace/actions/docker-login
      - name: Login to GitHub Container Registry
        #  if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      # Build the project and create Docker image
#      - name: Build Docker image
#        run: |
#          mvn spring-boot:build-image \
#          -DskipTests \
#          -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
#        # todo chatgpt: vreau sa modific astfel incat pe langa numele imaginii, sa fie adaugate tagurile produse mai sus
#
      # Build the project and create Docker image
      - name: Build Docker image
        run: |
          # Build the image with a temporary tag
          mvn spring-boot:build-image \
            -DskipTests \
            -Dspring-boot.build-image.imageName=${{ env.REGISTRY }}/${{ github.repository }}:temp-tag

      # Debugging step: Print the generated tags
      - name: Print Docker tags
        run: echo ${{ steps.meta.outputs.tags }}

      # Tag the Docker image with the tags generated by docker/metadata-action
      - name: Tag Docker image
        run: |
          TAGS=$(echo ${{ steps.meta.outputs.tags }} | tr ',' '\n')
          for TAG in $TAGS; do
            docker tag ${{ env.REGISTRY }}/${{ github.repository }}:temp-tag ${{ env.REGISTRY }}/${{ github.repository }}:$TAG
          done
      

      # Push Docker image to GitHub Container Registry
      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.DOCKER_METADATA_OUTPUT_VERSION }}
