name: Docker - Build Spring Boot Image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # Checkout: https://github.com/marketplace?type=actions:
      - name: Checkout
        uses: actions/checkout@v4z

      ## JAVA & maven related:
      # Setup JAVA JDK: https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Alternative: 'zulu'
          java-version: '21'

      # Build the project and create Docker image
      - name: Build with Maven and create Docker image
        run: mvn spring-boot:build-image

      # Docker Login: https://github.com/marketplace/actions/docker-login
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Docker Metadata action: https://github.com/marketplace/actions/docker-metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker images: https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
