name: Docker - Build Spring Boot Image - try 2

on:
  push:
    branches:
      - main  # Rulează pe push în branch-ul principal
    tags:
      - 'v*'  # Opțional, pentru a construi pe baza tag-urilor

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout: https://github.com/marketplace?type=actions:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup JAVA JDK: https://github.com/marketplace/actions/setup-java-jdk
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Alternative: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Build and push Docker image to GHCR
        run: mvn spring-boot:build-image -DskipTests
        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: ghcr.io/arcdz/${{ github.event.repository.name }}:${{ github.event.inputs.version || github.sha }}
          JAVA_VERSION: '21'
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}  # Utilizează token-ul implicit de GitHub
          DOCKER_USERNAME: ${{ github.actor }}           # Utilizatorul curent GitHub

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push $IMAGE_NAME
